apiVersion: v1
kind: Service
metadata:
    name: service-mysql
spec:
    ports:
        - name: mysql-port
          port: 3306
          targetPort: 3306
    selector:
        app: mysql-pod
    type: ClusterIP
