apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      tier: app
  template:
    metadata:
      labels:
        app: wordpress
        tier: app
    spec:
      containers:
        - name: wordpress
          image: wordpress

---
apiVersion: v1
kind: Service
metadata:
  name: wp-np
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      nodePort: 30000
  selector:
    app: wordpress
    tier: app
